import FeedbackCard from "../../components/FeedbackCard/feedbackCard";
import "./ratings.css";

const Ratings = () => {
    return (
        <div className="ratings-section">
            <h1>Ratings and Reviews</h1>
            <div className="contents">
                <FeedbackCard username="User123" message="Exceptional customer service! The representative was knowledgeable, attentive, and went above and beyond to address my needs. Highly recommended!" dateStamp="2023-01-12" image={"https://firebasestorage.googleapis.com/v0/b/pengeako-862f8.appspot.com/o/Images%2Fuser_placeholder.png?alt=media&token=830ea0d8-bbf9-4a68-b552-a6f6e313e6b1"} />
                <FeedbackCard username="User123" message="Exceptional customer service! The representative was knowledgeable, attentive, and went above and beyond to address my needs. Highly recommended!" dateStamp="2023-01-12" image={"https://firebasestorage.googleapis.com/v0/b/pengeako-862f8.appspot.com/o/Images%2Fuser_placeholder.png?alt=media&token=830ea0d8-bbf9-4a68-b552-a6f6e313e6b1"} />
                <FeedbackCard username="User123" message="Exceptional customer service! The representative was knowledgeable, attentive, and went above and beyond to address my needs. Highly recommended!" dateStamp="2023-01-12" image={"https://firebasestorage.googleapis.com/v0/b/pengeako-862f8.appspot.com/o/Images%2Fuser_placeholder.png?alt=media&token=830ea0d8-bbf9-4a68-b552-a6f6e313e6b1"} />
                <FeedbackCard username="User123" message="Exceptional customer service! The representative was knowledgeable, attentive, and went above and beyond to address my needs. Highly recommended!" dateStamp="2023-01-12" image={"https://firebasestorage.googleapis.com/v0/b/pengeako-862f8.appspot.com/o/Images%2Fuser_placeholder.png?alt=media&token=830ea0d8-bbf9-4a68-b552-a6f6e313e6b1"} />
                <FeedbackCard username="User123" message="Exceptional customer service! The representative was knowledgeable, attentive, and went above and beyond to address my needs. Highly recommended!" dateStamp="2023-01-12" image={"https://firebasestorage.googleapis.com/v0/b/pengeako-862f8.appspot.com/o/Images%2Fuser_placeholder.png?alt=media&token=830ea0d8-bbf9-4a68-b552-a6f6e313e6b1"} />
                <FeedbackCard username="User123" message="Exceptional customer service! The representative was knowledgeable, attentive, and went above and beyond to address my needs. Highly recommended!" dateStamp="2023-01-12" image={"https://firebasestorage.googleapis.com/v0/b/pengeako-862f8.appspot.com/o/Images%2Fuser_placeholder.png?alt=media&token=830ea0d8-bbf9-4a68-b552-a6f6e313e6b1"} />
                <FeedbackCard username="User123" message="Exceptional customer service! The representative was knowledgeable, attentive, and went above and beyond to address my needs. Highly recommended!" dateStamp="2023-01-12" image={"https://firebasestorage.googleapis.com/v0/b/pengeako-862f8.appspot.com/o/Images%2Fuser_placeholder.png?alt=media&token=830ea0d8-bbf9-4a68-b552-a6f6e313e6b1"} />
                <FeedbackCard username="User123" message="Exceptional customer service! The representative was knowledgeable, attentive, and went above and beyond to address my needs. Highly recommended!" dateStamp="2023-01-12" image={"https://firebasestorage.googleapis.com/v0/b/pengeako-862f8.appspot.com/o/Images%2Fuser_placeholder.png?alt=media&token=830ea0d8-bbf9-4a68-b552-a6f6e313e6b1"} />
                <FeedbackCard username="User123" message="Exceptional customer service! The representative was knowledgeable, attentive, and went above and beyond to address my needs. Highly recommended!" dateStamp="2023-01-12" image={"https://firebasestorage.googleapis.com/v0/b/pengeako-862f8.appspot.com/o/Images%2Fuser_placeholder.png?alt=media&token=830ea0d8-bbf9-4a68-b552-a6f6e313e6b1"} />
                <FeedbackCard username="User123" message="Exceptional customer service! The representative was knowledgeable, attentive, and went above and beyond to address my needs. Highly recommended!" dateStamp="2023-01-12" image={"https://firebasestorage.googleapis.com/v0/b/pengeako-862f8.appspot.com/o/Images%2Fuser_placeholder.png?alt=media&token=830ea0d8-bbf9-4a68-b552-a6f6e313e6b1"} />
                <FeedbackCard username="User123" message="Exceptional customer service! The representative was knowledgeable, attentive, and went above and beyond to address my needs. Highly recommended!" dateStamp="2023-01-12" image={"https://firebasestorage.googleapis.com/v0/b/pengeako-862f8.appspot.com/o/Images%2Fuser_placeholder.png?alt=media&token=830ea0d8-bbf9-4a68-b552-a6f6e313e6b1"} />
                <FeedbackCard username="User123" message="Exceptional customer service! The representative was knowledgeable, attentive, and went above and beyond to address my needs. Highly recommended!" dateStamp="2023-01-12" image={"https://firebasestorage.googleapis.com/v0/b/pengeako-862f8.appspot.com/o/Images%2Fuser_placeholder.png?alt=media&token=830ea0d8-bbf9-4a68-b552-a6f6e313e6b1"} />
                <FeedbackCard username="User123" message="Exceptional customer service! The representative was knowledgeable, attentive, and went above and beyond to address my needs. Highly recommended!" dateStamp="2023-01-12" image={"https://firebasestorage.googleapis.com/v0/b/pengeako-862f8.appspot.com/o/Images%2Fuser_placeholder.png?alt=media&token=830ea0d8-bbf9-4a68-b552-a6f6e313e6b1"} />
                <FeedbackCard username="User123" message="Exceptional customer service! The representative was knowledgeable, attentive, and went above and beyond to address my needs. Highly recommended!" dateStamp="2023-01-12" image={"https://firebasestorage.googleapis.com/v0/b/pengeako-862f8.appspot.com/o/Images%2Fuser_placeholder.png?alt=media&token=830ea0d8-bbf9-4a68-b552-a6f6e313e6b1"} />
                <FeedbackCard username="User123" message="Exceptional customer service! The representative was knowledgeable, attentive, and went above and beyond to address my needs. Highly recommended!" dateStamp="2023-01-12" image={"https://firebasestorage.googleapis.com/v0/b/pengeako-862f8.appspot.com/o/Images%2Fuser_placeholder.png?alt=media&token=830ea0d8-bbf9-4a68-b552-a6f6e313e6b1"} />
            </div>
        </div>
    );
}

export default Ratings;